[images]
  remote_images = ["https://cdn.jsdelivr.net/*", "https://img.icons8.com/*", "https://dicoding-web-img.sgp1.cdn.digitaloceanspaces.com/*", "https://images.unsplash.com/*"]

[build]
  command = "bun run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--version"
  NEXT_USE_NETLIFY_EDGE = "true"
  NODE_OPTIONS = "--max_old_space_size=4096"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-eval' 'unsafe-inline'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; img-src 'self' data: https: https://*.githubusercontent.com https://*.unsplash.com; font-src 'self' https://fonts.gstatic.com; connect-src 'self' https://api.github.com; frame-src 'self'"

[[plugins]]
  package = "@netlify/plugin-nextjs"
